sudo: required
language: ruby
env:
  - DATABASE_URL="postgresql://postgres@localhost/upsert_test"
rvm:
  - 2.3.1
before_script:
  - createdb --echo -U postgres upsert_test
  - psql -U postgres upsert_test < spec/dummy/db/structure.sql

before_install: gem install bundler -v 1.13.3

addons:
  postgresql: "9.5"

